// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/account.dart';
import 'api/coin.dart';
import 'api/contacts.dart';
import 'api/db.dart';
import 'api/frost.dart';
import 'api/init.dart';
import 'api/issuance.dart';
import 'api/key.dart';
import 'api/mempool.dart';
import 'api/migrate.dart';
import 'api/network.dart';
import 'api/openalias.dart';
import 'api/pay.dart';
import 'api/plugin.dart';
import 'api/raptor.dart';
import 'api/sapling.dart';
import 'api/sweep.dart';
import 'api/sync.dart';
import 'api/transaction.dart';
import 'api/vault.dart';
import 'api/voting.dart';
import 'api/zsa.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'io.dart';
import 'lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';
import 'pay.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_DartVaultPtr =>
      wire._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDartVaultPtr;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_MempoolPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMempoolPtr;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_NoteMigrationPtr => wire
          ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNoteMigrationPtr;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_TransparentScannerPtr => wire
          ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTransparentScannerPtr;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  DartVault
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDartVault(
          dynamic raw);

  @protected
  Mempool
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMempool(
          dynamic raw);

  @protected
  NoteMigration
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNoteMigration(
          dynamic raw);

  @protected
  TransparentScanner
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTransparentScanner(
          dynamic raw);

  @protected
  Mempool
      dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMempool(
          dynamic raw);

  @protected
  TransparentScanner
      dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTransparentScanner(
          dynamic raw);

  @protected
  DartVault
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDartVault(
          dynamic raw);

  @protected
  NoteMigration
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNoteMigration(
          dynamic raw);

  @protected
  TransparentScanner
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTransparentScanner(
          dynamic raw);

  @protected
  FutureOr<void> Function(Uint8List)
      dco_decode_DartFn_Inputs_list_prim_u_8_strict_Output_unit_AnyhowException(
          dynamic raw);

  @protected
  Object dco_decode_DartOpaque(dynamic raw);

  @protected
  DartVault
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDartVault(
          dynamic raw);

  @protected
  Mempool
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMempool(
          dynamic raw);

  @protected
  NoteMigration
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNoteMigration(
          dynamic raw);

  @protected
  TransparentScanner
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTransparentScanner(
          dynamic raw);

  @protected
  RustStreamSink<String> dco_decode_StreamSink_String_Sse(dynamic raw);

  @protected
  RustStreamSink<DKGStatus> dco_decode_StreamSink_dkg_status_Sse(dynamic raw);

  @protected
  RustStreamSink<LogMessage> dco_decode_StreamSink_log_message_Sse(dynamic raw);

  @protected
  RustStreamSink<MempoolMsg> dco_decode_StreamSink_mempool_msg_Sse(dynamic raw);

  @protected
  RustStreamSink<MigrationStatus> dco_decode_StreamSink_migration_status_Sse(
      dynamic raw);

  @protected
  RustStreamSink<SigningEvent> dco_decode_StreamSink_signing_event_Sse(
      dynamic raw);

  @protected
  RustStreamSink<SigningStatus> dco_decode_StreamSink_signing_status_Sse(
      dynamic raw);

  @protected
  RustStreamSink<SyncProgress> dco_decode_StreamSink_sync_progress_Sse(
      dynamic raw);

  @protected
  RustStreamSink<VotingDelegationProgress>
      dco_decode_StreamSink_voting_delegation_progress_Sse(dynamic raw);

  @protected
  RustStreamSink<VotingVoteCommitStage>
      dco_decode_StreamSink_voting_vote_commit_stage_Sse(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  Account dco_decode_account(dynamic raw);

  @protected
  AccountUpdate dco_decode_account_update(dynamic raw);

  @protected
  Addresses dco_decode_addresses(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  AccountUpdate dco_decode_box_autoadd_account_update(dynamic raw);

  @protected
  bool dco_decode_box_autoadd_bool(dynamic raw);

  @protected
  Category dco_decode_box_autoadd_category(dynamic raw);

  @protected
  Coin dco_decode_box_autoadd_coin(dynamic raw);

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw);

  @protected
  FrostParams dco_decode_box_autoadd_frost_params(dynamic raw);

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  MempoolTx dco_decode_box_autoadd_mempool_tx(dynamic raw);

  @protected
  NewAccount dco_decode_box_autoadd_new_account(dynamic raw);

  @protected
  PaymentOptions dco_decode_box_autoadd_payment_options(dynamic raw);

  @protected
  PcztPackage dco_decode_box_autoadd_pczt_package(dynamic raw);

  @protected
  RaptorQParams dco_decode_box_autoadd_raptor_q_params(dynamic raw);

  @protected
  Seed dco_decode_box_autoadd_seed(dynamic raw);

  @protected
  SigningEvent dco_decode_box_autoadd_signing_event(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_8(dynamic raw);

  @protected
  VotingCompletedVoteDisplay
      dco_decode_box_autoadd_voting_completed_vote_display(dynamic raw);

  @protected
  VotingConfig dco_decode_box_autoadd_voting_config(dynamic raw);

  @protected
  VotingPirLayout dco_decode_box_autoadd_voting_pir_layout(dynamic raw);

  @protected
  Category dco_decode_category(dynamic raw);

  @protected
  Coin dco_decode_coin(dynamic raw);

  @protected
  Contact dco_decode_contact(dynamic raw);

  @protected
  ContactMatch dco_decode_contact_match(dynamic raw);

  @protected
  DbAccountPreview dco_decode_db_account_preview(dynamic raw);

  @protected
  DKGStatus dco_decode_dkg_status(dynamic raw);

  @protected
  ExchangeRate dco_decode_exchange_rate(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  Folder dco_decode_folder(dynamic raw);

  @protected
  FrostParams dco_decode_frost_params(dynamic raw);

  @protected
  FrostSignParams dco_decode_frost_sign_params(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  PlatformInt64 dco_decode_isize(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<Account> dco_decode_list_account(dynamic raw);

  @protected
  List<Category> dco_decode_list_category(dynamic raw);

  @protected
  List<Contact> dco_decode_list_contact(dynamic raw);

  @protected
  List<ContactMatch> dco_decode_list_contact_match(dynamic raw);

  @protected
  List<DbAccountPreview> dco_decode_list_db_account_preview(dynamic raw);

  @protected
  List<Folder> dco_decode_list_folder(dynamic raw);

  @protected
  List<Uint8List> dco_decode_list_list_prim_u_8_strict(dynamic raw);

  @protected
  List<LWDInfo> dco_decode_list_lwd_info(dynamic raw);

  @protected
  List<Memo> dco_decode_list_memo(dynamic raw);

  @protected
  List<MemoCell> dco_decode_list_memo_cell(dynamic raw);

  @protected
  List<MemoRow> dco_decode_list_memo_row(dynamic raw);

  @protected
  List<MemoSection> dco_decode_list_memo_section(dynamic raw);

  @protected
  List<MempoolAmount> dco_decode_list_mempool_amount(dynamic raw);

  @protected
  List<MempoolNote> dco_decode_list_mempool_note(dynamic raw);

  @protected
  List<PluginInfo> dco_decode_list_plugin_info(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_32_loose(dynamic raw);

  @protected
  Uint32List dco_decode_list_prim_u_32_strict(dynamic raw);

  @protected
  Uint64List dco_decode_list_prim_u_64_strict(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  Uint64List dco_decode_list_prim_usize_strict(dynamic raw);

  @protected
  List<Recipient> dco_decode_list_recipient(dynamic raw);

  @protected
  List<(String, double, bool)> dco_decode_list_record_string_f_64_bool(
      dynamic raw);

  @protected
  List<(int, double)> dco_decode_list_record_u_32_f_64(dynamic raw);

  @protected
  List<RestoredAccount> dco_decode_list_restored_account(dynamic raw);

  @protected
  List<TAddressTxCount> dco_decode_list_t_address_tx_count(dynamic raw);

  @protected
  List<Tx> dco_decode_list_tx(dynamic raw);

  @protected
  List<TxMemo> dco_decode_list_tx_memo(dynamic raw);

  @protected
  List<TxNote> dco_decode_list_tx_note(dynamic raw);

  @protected
  List<TxOutput> dco_decode_list_tx_output(dynamic raw);

  @protected
  List<TxPlanIn> dco_decode_list_tx_plan_in(dynamic raw);

  @protected
  List<TxPlanOut> dco_decode_list_tx_plan_out(dynamic raw);

  @protected
  List<TxSpend> dco_decode_list_tx_spend(dynamic raw);

  @protected
  List<VotingBallotIntent> dco_decode_list_voting_ballot_intent(dynamic raw);

  @protected
  List<VotingCompletedVoteChoice> dco_decode_list_voting_completed_vote_choice(
      dynamic raw);

  @protected
  List<VotingConfigRound> dco_decode_list_voting_config_round(dynamic raw);

  @protected
  List<VotingDelegationRecovery> dco_decode_list_voting_delegation_recovery(
      dynamic raw);

  @protected
  List<VotingDelegationStatus> dco_decode_list_voting_delegation_status(
      dynamic raw);

  @protected
  List<VotingEncryptedShare> dco_decode_list_voting_encrypted_share(
      dynamic raw);

  @protected
  List<VotingNextStep> dco_decode_list_voting_next_step(dynamic raw);

  @protected
  List<VotingRoundInfo> dco_decode_list_voting_round_info(dynamic raw);

  @protected
  List<VotingRoundSession> dco_decode_list_voting_round_session(dynamic raw);

  @protected
  List<VotingServiceEndpoint> dco_decode_list_voting_service_endpoint(
      dynamic raw);

  @protected
  List<VotingShareDelegationRecord>
      dco_decode_list_voting_share_delegation_record(dynamic raw);

  @protected
  List<VotingSharePayload> dco_decode_list_voting_share_payload(dynamic raw);

  @protected
  List<VotingSharePlanItem> dco_decode_list_voting_share_plan_item(dynamic raw);

  @protected
  List<VotingShareSubmissionPayload>
      dco_decode_list_voting_share_submission_payload(dynamic raw);

  @protected
  List<VotingShareWorkflow> dco_decode_list_voting_share_workflow(dynamic raw);

  @protected
  List<VotingSignedVoteCommitment>
      dco_decode_list_voting_signed_vote_commitment(dynamic raw);

  @protected
  List<VotingVoteRecovery> dco_decode_list_voting_vote_recovery(dynamic raw);

  @protected
  List<ZsaHolding> dco_decode_list_zsa_holding(dynamic raw);

  @protected
  LogMessage dco_decode_log_message(dynamic raw);

  @protected
  LWDInfo dco_decode_lwd_info(dynamic raw);

  @protected
  Memo dco_decode_memo(dynamic raw);

  @protected
  MemoCell dco_decode_memo_cell(dynamic raw);

  @protected
  MemoRow dco_decode_memo_row(dynamic raw);

  @protected
  MemoSection dco_decode_memo_section(dynamic raw);

  @protected
  MempoolAmount dco_decode_mempool_amount(dynamic raw);

  @protected
  MempoolMsg dco_decode_mempool_msg(dynamic raw);

  @protected
  MempoolNote dco_decode_mempool_note(dynamic raw);

  @protected
  MempoolTx dco_decode_mempool_tx(dynamic raw);

  @protected
  MigrationEvent dco_decode_migration_event(dynamic raw);

  @protected
  MigrationStatus dco_decode_migration_status(dynamic raw);

  @protected
  NewAccount dco_decode_new_account(dynamic raw);

  @protected
  OpenAliasResolution dco_decode_open_alias_resolution(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  bool? dco_decode_opt_box_autoadd_bool(dynamic raw);

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw);

  @protected
  FrostParams? dco_decode_opt_box_autoadd_frost_params(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  Seed? dco_decode_opt_box_autoadd_seed(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_8(dynamic raw);

  @protected
  VotingCompletedVoteDisplay?
      dco_decode_opt_box_autoadd_voting_completed_vote_display(dynamic raw);

  @protected
  VotingConfig? dco_decode_opt_box_autoadd_voting_config(dynamic raw);

  @protected
  VotingPirLayout? dco_decode_opt_box_autoadd_voting_pir_layout(dynamic raw);

  @protected
  List<String>? dco_decode_opt_list_String(dynamic raw);

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw);

  @protected
  List<Recipient>? dco_decode_opt_list_recipient(dynamic raw);

  @protected
  PaymentOptions dco_decode_payment_options(dynamic raw);

  @protected
  PcztPackage dco_decode_pczt_package(dynamic raw);

  @protected
  PluginInfo dco_decode_plugin_info(dynamic raw);

  @protected
  PoolBalance dco_decode_pool_balance(dynamic raw);

  @protected
  RaptorQParams dco_decode_raptor_q_params(dynamic raw);

  @protected
  RawOpenAliasResolution dco_decode_raw_open_alias_resolution(dynamic raw);

  @protected
  Receivers dco_decode_receivers(dynamic raw);

  @protected
  Recipient dco_decode_recipient(dynamic raw);

  @protected
  (String, double, bool) dco_decode_record_string_f_64_bool(dynamic raw);

  @protected
  (int, double) dco_decode_record_u_32_f_64(dynamic raw);

  @protected
  RestoredAccount dco_decode_restored_account(dynamic raw);

  @protected
  SaplingParamsStatus dco_decode_sapling_params_status(dynamic raw);

  @protected
  Seed dco_decode_seed(dynamic raw);

  @protected
  SigningEvent dco_decode_signing_event(dynamic raw);

  @protected
  SigningStatus dco_decode_signing_status(dynamic raw);

  @protected
  SyncHeight dco_decode_sync_height(dynamic raw);

  @protected
  SyncProgress dco_decode_sync_progress(dynamic raw);

  @protected
  TAddressTxCount dco_decode_t_address_tx_count(dynamic raw);

  @protected
  Tx dco_decode_tx(dynamic raw);

  @protected
  TxAccount dco_decode_tx_account(dynamic raw);

  @protected
  TxMemo dco_decode_tx_memo(dynamic raw);

  @protected
  TxNote dco_decode_tx_note(dynamic raw);

  @protected
  TxOutput dco_decode_tx_output(dynamic raw);

  @protected
  TxPlan dco_decode_tx_plan(dynamic raw);

  @protected
  TxPlanIn dco_decode_tx_plan_in(dynamic raw);

  @protected
  TxPlanOut dco_decode_tx_plan_out(dynamic raw);

  @protected
  TxSpend dco_decode_tx_spend(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  UsizeArray4 dco_decode_usize_array_4(dynamic raw);

  @protected
  VotingBallotIntent dco_decode_voting_ballot_intent(dynamic raw);

  @protected
  VotingChainResponse dco_decode_voting_chain_response(dynamic raw);

  @protected
  VotingCompletedVoteChoice dco_decode_voting_completed_vote_choice(
      dynamic raw);

  @protected
  VotingCompletedVoteDisplay dco_decode_voting_completed_vote_display(
      dynamic raw);

  @protected
  VotingConfig dco_decode_voting_config(dynamic raw);

  @protected
  VotingConfigRound dco_decode_voting_config_round(dynamic raw);

  @protected
  VotingDelegationBuild dco_decode_voting_delegation_build(dynamic raw);

  @protected
  VotingDelegationConfirmation dco_decode_voting_delegation_confirmation(
      dynamic raw);

  @protected
  VotingDelegationProgress dco_decode_voting_delegation_progress(dynamic raw);

  @protected
  VotingDelegationRecovery dco_decode_voting_delegation_recovery(dynamic raw);

  @protected
  VotingDelegationSetup dco_decode_voting_delegation_setup(dynamic raw);

  @protected
  VotingDelegationStatus dco_decode_voting_delegation_status(dynamic raw);

  @protected
  VotingDelegationSubmission dco_decode_voting_delegation_submission(
      dynamic raw);

  @protected
  VotingEncryptedShare dco_decode_voting_encrypted_share(dynamic raw);

  @protected
  VotingNextStep dco_decode_voting_next_step(dynamic raw);

  @protected
  VotingPirLayout dco_decode_voting_pir_layout(dynamic raw);

  @protected
  VotingPreparedInfo dco_decode_voting_prepared_info(dynamic raw);

  @protected
  VotingRoundInfo dco_decode_voting_round_info(dynamic raw);

  @protected
  VotingRoundPlan dco_decode_voting_round_plan(dynamic raw);

  @protected
  VotingRoundRecovery dco_decode_voting_round_recovery(dynamic raw);

  @protected
  VotingRoundSession dco_decode_voting_round_session(dynamic raw);

  @protected
  VotingServiceEndpoint dco_decode_voting_service_endpoint(dynamic raw);

  @protected
  VotingShareDelegationRecord dco_decode_voting_share_delegation_record(
      dynamic raw);

  @protected
  VotingSharePayload dco_decode_voting_share_payload(dynamic raw);

  @protected
  VotingSharePlan dco_decode_voting_share_plan(dynamic raw);

  @protected
  VotingSharePlanItem dco_decode_voting_share_plan_item(dynamic raw);

  @protected
  VotingShareSubmissionPayload dco_decode_voting_share_submission_payload(
      dynamic raw);

  @protected
  VotingShareTrackingSummary dco_decode_voting_share_tracking_summary(
      dynamic raw);

  @protected
  VotingShareWorkflow dco_decode_voting_share_workflow(dynamic raw);

  @protected
  VotingSignedVoteCommitment dco_decode_voting_signed_vote_commitment(
      dynamic raw);

  @protected
  VotingTreeVoteConfirmation dco_decode_voting_tree_vote_confirmation(
      dynamic raw);

  @protected
  VotingVanWitness dco_decode_voting_van_witness(dynamic raw);

  @protected
  VotingVoteCommitStage dco_decode_voting_vote_commit_stage(dynamic raw);

  @protected
  VotingVoteCommitments dco_decode_voting_vote_commitments(dynamic raw);

  @protected
  VotingVoteConfirmation dco_decode_voting_vote_confirmation(dynamic raw);

  @protected
  VotingVotePayloads dco_decode_voting_vote_payloads(dynamic raw);

  @protected
  VotingVoteRecovery dco_decode_voting_vote_recovery(dynamic raw);

  @protected
  VotingVoteSubmission dco_decode_voting_vote_submission(dynamic raw);

  @protected
  ZsaHolding dco_decode_zsa_holding(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  DartVault
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDartVault(
          SseDeserializer deserializer);

  @protected
  Mempool
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMempool(
          SseDeserializer deserializer);

  @protected
  NoteMigration
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNoteMigration(
          SseDeserializer deserializer);

  @protected
  TransparentScanner
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTransparentScanner(
          SseDeserializer deserializer);

  @protected
  Mempool
      sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMempool(
          SseDeserializer deserializer);

  @protected
  TransparentScanner
      sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTransparentScanner(
          SseDeserializer deserializer);

  @protected
  DartVault
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDartVault(
          SseDeserializer deserializer);

  @protected
  NoteMigration
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNoteMigration(
          SseDeserializer deserializer);

  @protected
  TransparentScanner
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTransparentScanner(
          SseDeserializer deserializer);

  @protected
  Object sse_decode_DartOpaque(SseDeserializer deserializer);

  @protected
  DartVault
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDartVault(
          SseDeserializer deserializer);

  @protected
  Mempool
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMempool(
          SseDeserializer deserializer);

  @protected
  NoteMigration
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNoteMigration(
          SseDeserializer deserializer);

  @protected
  TransparentScanner
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTransparentScanner(
          SseDeserializer deserializer);

  @protected
  RustStreamSink<String> sse_decode_StreamSink_String_Sse(
      SseDeserializer deserializer);

  @protected
  RustStreamSink<DKGStatus> sse_decode_StreamSink_dkg_status_Sse(
      SseDeserializer deserializer);

  @protected
  RustStreamSink<LogMessage> sse_decode_StreamSink_log_message_Sse(
      SseDeserializer deserializer);

  @protected
  RustStreamSink<MempoolMsg> sse_decode_StreamSink_mempool_msg_Sse(
      SseDeserializer deserializer);

  @protected
  RustStreamSink<MigrationStatus> sse_decode_StreamSink_migration_status_Sse(
      SseDeserializer deserializer);

  @protected
  RustStreamSink<SigningEvent> sse_decode_StreamSink_signing_event_Sse(
      SseDeserializer deserializer);

  @protected
  RustStreamSink<SigningStatus> sse_decode_StreamSink_signing_status_Sse(
      SseDeserializer deserializer);

  @protected
  RustStreamSink<SyncProgress> sse_decode_StreamSink_sync_progress_Sse(
      SseDeserializer deserializer);

  @protected
  RustStreamSink<VotingDelegationProgress>
      sse_decode_StreamSink_voting_delegation_progress_Sse(
          SseDeserializer deserializer);

  @protected
  RustStreamSink<VotingVoteCommitStage>
      sse_decode_StreamSink_voting_vote_commit_stage_Sse(
          SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  Account sse_decode_account(SseDeserializer deserializer);

  @protected
  AccountUpdate sse_decode_account_update(SseDeserializer deserializer);

  @protected
  Addresses sse_decode_addresses(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  AccountUpdate sse_decode_box_autoadd_account_update(
      SseDeserializer deserializer);

  @protected
  bool sse_decode_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  Category sse_decode_box_autoadd_category(SseDeserializer deserializer);

  @protected
  Coin sse_decode_box_autoadd_coin(SseDeserializer deserializer);

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  FrostParams sse_decode_box_autoadd_frost_params(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  MempoolTx sse_decode_box_autoadd_mempool_tx(SseDeserializer deserializer);

  @protected
  NewAccount sse_decode_box_autoadd_new_account(SseDeserializer deserializer);

  @protected
  PaymentOptions sse_decode_box_autoadd_payment_options(
      SseDeserializer deserializer);

  @protected
  PcztPackage sse_decode_box_autoadd_pczt_package(SseDeserializer deserializer);

  @protected
  RaptorQParams sse_decode_box_autoadd_raptor_q_params(
      SseDeserializer deserializer);

  @protected
  Seed sse_decode_box_autoadd_seed(SseDeserializer deserializer);

  @protected
  SigningEvent sse_decode_box_autoadd_signing_event(
      SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_8(SseDeserializer deserializer);

  @protected
  VotingCompletedVoteDisplay
      sse_decode_box_autoadd_voting_completed_vote_display(
          SseDeserializer deserializer);

  @protected
  VotingConfig sse_decode_box_autoadd_voting_config(
      SseDeserializer deserializer);

  @protected
  VotingPirLayout sse_decode_box_autoadd_voting_pir_layout(
      SseDeserializer deserializer);

  @protected
  Category sse_decode_category(SseDeserializer deserializer);

  @protected
  Coin sse_decode_coin(SseDeserializer deserializer);

  @protected
  Contact sse_decode_contact(SseDeserializer deserializer);

  @protected
  ContactMatch sse_decode_contact_match(SseDeserializer deserializer);

  @protected
  DbAccountPreview sse_decode_db_account_preview(SseDeserializer deserializer);

  @protected
  DKGStatus sse_decode_dkg_status(SseDeserializer deserializer);

  @protected
  ExchangeRate sse_decode_exchange_rate(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  Folder sse_decode_folder(SseDeserializer deserializer);

  @protected
  FrostParams sse_decode_frost_params(SseDeserializer deserializer);

  @protected
  FrostSignParams sse_decode_frost_sign_params(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_isize(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<Account> sse_decode_list_account(SseDeserializer deserializer);

  @protected
  List<Category> sse_decode_list_category(SseDeserializer deserializer);

  @protected
  List<Contact> sse_decode_list_contact(SseDeserializer deserializer);

  @protected
  List<ContactMatch> sse_decode_list_contact_match(
      SseDeserializer deserializer);

  @protected
  List<DbAccountPreview> sse_decode_list_db_account_preview(
      SseDeserializer deserializer);

  @protected
  List<Folder> sse_decode_list_folder(SseDeserializer deserializer);

  @protected
  List<Uint8List> sse_decode_list_list_prim_u_8_strict(
      SseDeserializer deserializer);

  @protected
  List<LWDInfo> sse_decode_list_lwd_info(SseDeserializer deserializer);

  @protected
  List<Memo> sse_decode_list_memo(SseDeserializer deserializer);

  @protected
  List<MemoCell> sse_decode_list_memo_cell(SseDeserializer deserializer);

  @protected
  List<MemoRow> sse_decode_list_memo_row(SseDeserializer deserializer);

  @protected
  List<MemoSection> sse_decode_list_memo_section(SseDeserializer deserializer);

  @protected
  List<MempoolAmount> sse_decode_list_mempool_amount(
      SseDeserializer deserializer);

  @protected
  List<MempoolNote> sse_decode_list_mempool_note(SseDeserializer deserializer);

  @protected
  List<PluginInfo> sse_decode_list_plugin_info(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_32_loose(SseDeserializer deserializer);

  @protected
  Uint32List sse_decode_list_prim_u_32_strict(SseDeserializer deserializer);

  @protected
  Uint64List sse_decode_list_prim_u_64_strict(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  Uint64List sse_decode_list_prim_usize_strict(SseDeserializer deserializer);

  @protected
  List<Recipient> sse_decode_list_recipient(SseDeserializer deserializer);

  @protected
  List<(String, double, bool)> sse_decode_list_record_string_f_64_bool(
      SseDeserializer deserializer);

  @protected
  List<(int, double)> sse_decode_list_record_u_32_f_64(
      SseDeserializer deserializer);

  @protected
  List<RestoredAccount> sse_decode_list_restored_account(
      SseDeserializer deserializer);

  @protected
  List<TAddressTxCount> sse_decode_list_t_address_tx_count(
      SseDeserializer deserializer);

  @protected
  List<Tx> sse_decode_list_tx(SseDeserializer deserializer);

  @protected
  List<TxMemo> sse_decode_list_tx_memo(SseDeserializer deserializer);

  @protected
  List<TxNote> sse_decode_list_tx_note(SseDeserializer deserializer);

  @protected
  List<TxOutput> sse_decode_list_tx_output(SseDeserializer deserializer);

  @protected
  List<TxPlanIn> sse_decode_list_tx_plan_in(SseDeserializer deserializer);

  @protected
  List<TxPlanOut> sse_decode_list_tx_plan_out(SseDeserializer deserializer);

  @protected
  List<TxSpend> sse_decode_list_tx_spend(SseDeserializer deserializer);

  @protected
  List<VotingBallotIntent> sse_decode_list_voting_ballot_intent(
      SseDeserializer deserializer);

  @protected
  List<VotingCompletedVoteChoice> sse_decode_list_voting_completed_vote_choice(
      SseDeserializer deserializer);

  @protected
  List<VotingConfigRound> sse_decode_list_voting_config_round(
      SseDeserializer deserializer);

  @protected
  List<VotingDelegationRecovery> sse_decode_list_voting_delegation_recovery(
      SseDeserializer deserializer);

  @protected
  List<VotingDelegationStatus> sse_decode_list_voting_delegation_status(
      SseDeserializer deserializer);

  @protected
  List<VotingEncryptedShare> sse_decode_list_voting_encrypted_share(
      SseDeserializer deserializer);

  @protected
  List<VotingNextStep> sse_decode_list_voting_next_step(
      SseDeserializer deserializer);

  @protected
  List<VotingRoundInfo> sse_decode_list_voting_round_info(
      SseDeserializer deserializer);

  @protected
  List<VotingRoundSession> sse_decode_list_voting_round_session(
      SseDeserializer deserializer);

  @protected
  List<VotingServiceEndpoint> sse_decode_list_voting_service_endpoint(
      SseDeserializer deserializer);

  @protected
  List<VotingShareDelegationRecord>
      sse_decode_list_voting_share_delegation_record(
          SseDeserializer deserializer);

  @protected
  List<VotingSharePayload> sse_decode_list_voting_share_payload(
      SseDeserializer deserializer);

  @protected
  List<VotingSharePlanItem> sse_decode_list_voting_share_plan_item(
      SseDeserializer deserializer);

  @protected
  List<VotingShareSubmissionPayload>
      sse_decode_list_voting_share_submission_payload(
          SseDeserializer deserializer);

  @protected
  List<VotingShareWorkflow> sse_decode_list_voting_share_workflow(
      SseDeserializer deserializer);

  @protected
  List<VotingSignedVoteCommitment>
      sse_decode_list_voting_signed_vote_commitment(
          SseDeserializer deserializer);

  @protected
  List<VotingVoteRecovery> sse_decode_list_voting_vote_recovery(
      SseDeserializer deserializer);

  @protected
  List<ZsaHolding> sse_decode_list_zsa_holding(SseDeserializer deserializer);

  @protected
  LogMessage sse_decode_log_message(SseDeserializer deserializer);

  @protected
  LWDInfo sse_decode_lwd_info(SseDeserializer deserializer);

  @protected
  Memo sse_decode_memo(SseDeserializer deserializer);

  @protected
  MemoCell sse_decode_memo_cell(SseDeserializer deserializer);

  @protected
  MemoRow sse_decode_memo_row(SseDeserializer deserializer);

  @protected
  MemoSection sse_decode_memo_section(SseDeserializer deserializer);

  @protected
  MempoolAmount sse_decode_mempool_amount(SseDeserializer deserializer);

  @protected
  MempoolMsg sse_decode_mempool_msg(SseDeserializer deserializer);

  @protected
  MempoolNote sse_decode_mempool_note(SseDeserializer deserializer);

  @protected
  MempoolTx sse_decode_mempool_tx(SseDeserializer deserializer);

  @protected
  MigrationEvent sse_decode_migration_event(SseDeserializer deserializer);

  @protected
  MigrationStatus sse_decode_migration_status(SseDeserializer deserializer);

  @protected
  NewAccount sse_decode_new_account(SseDeserializer deserializer);

  @protected
  OpenAliasResolution sse_decode_open_alias_resolution(
      SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  FrostParams? sse_decode_opt_box_autoadd_frost_params(
      SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  Seed? sse_decode_opt_box_autoadd_seed(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_8(SseDeserializer deserializer);

  @protected
  VotingCompletedVoteDisplay?
      sse_decode_opt_box_autoadd_voting_completed_vote_display(
          SseDeserializer deserializer);

  @protected
  VotingConfig? sse_decode_opt_box_autoadd_voting_config(
      SseDeserializer deserializer);

  @protected
  VotingPirLayout? sse_decode_opt_box_autoadd_voting_pir_layout(
      SseDeserializer deserializer);

  @protected
  List<String>? sse_decode_opt_list_String(SseDeserializer deserializer);

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<Recipient>? sse_decode_opt_list_recipient(SseDeserializer deserializer);

  @protected
  PaymentOptions sse_decode_payment_options(SseDeserializer deserializer);

  @protected
  PcztPackage sse_decode_pczt_package(SseDeserializer deserializer);

  @protected
  PluginInfo sse_decode_plugin_info(SseDeserializer deserializer);

  @protected
  PoolBalance sse_decode_pool_balance(SseDeserializer deserializer);

  @protected
  RaptorQParams sse_decode_raptor_q_params(SseDeserializer deserializer);

  @protected
  RawOpenAliasResolution sse_decode_raw_open_alias_resolution(
      SseDeserializer deserializer);

  @protected
  Receivers sse_decode_receivers(SseDeserializer deserializer);

  @protected
  Recipient sse_decode_recipient(SseDeserializer deserializer);

  @protected
  (String, double, bool) sse_decode_record_string_f_64_bool(
      SseDeserializer deserializer);

  @protected
  (int, double) sse_decode_record_u_32_f_64(SseDeserializer deserializer);

  @protected
  RestoredAccount sse_decode_restored_account(SseDeserializer deserializer);

  @protected
  SaplingParamsStatus sse_decode_sapling_params_status(
      SseDeserializer deserializer);

  @protected
  Seed sse_decode_seed(SseDeserializer deserializer);

  @protected
  SigningEvent sse_decode_signing_event(SseDeserializer deserializer);

  @protected
  SigningStatus sse_decode_signing_status(SseDeserializer deserializer);

  @protected
  SyncHeight sse_decode_sync_height(SseDeserializer deserializer);

  @protected
  SyncProgress sse_decode_sync_progress(SseDeserializer deserializer);

  @protected
  TAddressTxCount sse_decode_t_address_tx_count(SseDeserializer deserializer);

  @protected
  Tx sse_decode_tx(SseDeserializer deserializer);

  @protected
  TxAccount sse_decode_tx_account(SseDeserializer deserializer);

  @protected
  TxMemo sse_decode_tx_memo(SseDeserializer deserializer);

  @protected
  TxNote sse_decode_tx_note(SseDeserializer deserializer);

  @protected
  TxOutput sse_decode_tx_output(SseDeserializer deserializer);

  @protected
  TxPlan sse_decode_tx_plan(SseDeserializer deserializer);

  @protected
  TxPlanIn sse_decode_tx_plan_in(SseDeserializer deserializer);

  @protected
  TxPlanOut sse_decode_tx_plan_out(SseDeserializer deserializer);

  @protected
  TxSpend sse_decode_tx_spend(SseDeserializer deserializer);

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  UsizeArray4 sse_decode_usize_array_4(SseDeserializer deserializer);

  @protected
  VotingBallotIntent sse_decode_voting_ballot_intent(
      SseDeserializer deserializer);

  @protected
  VotingChainResponse sse_decode_voting_chain_response(
      SseDeserializer deserializer);

  @protected
  VotingCompletedVoteChoice sse_decode_voting_completed_vote_choice(
      SseDeserializer deserializer);

  @protected
  VotingCompletedVoteDisplay sse_decode_voting_completed_vote_display(
      SseDeserializer deserializer);

  @protected
  VotingConfig sse_decode_voting_config(SseDeserializer deserializer);

  @protected
  VotingConfigRound sse_decode_voting_config_round(
      SseDeserializer deserializer);

  @protected
  VotingDelegationBuild sse_decode_voting_delegation_build(
      SseDeserializer deserializer);

  @protected
  VotingDelegationConfirmation sse_decode_voting_delegation_confirmation(
      SseDeserializer deserializer);

  @protected
  VotingDelegationProgress sse_decode_voting_delegation_progress(
      SseDeserializer deserializer);

  @protected
  VotingDelegationRecovery sse_decode_voting_delegation_recovery(
      SseDeserializer deserializer);

  @protected
  VotingDelegationSetup sse_decode_voting_delegation_setup(
      SseDeserializer deserializer);

  @protected
  VotingDelegationStatus sse_decode_voting_delegation_status(
      SseDeserializer deserializer);

  @protected
  VotingDelegationSubmission sse_decode_voting_delegation_submission(
      SseDeserializer deserializer);

  @protected
  VotingEncryptedShare sse_decode_voting_encrypted_share(
      SseDeserializer deserializer);

  @protected
  VotingNextStep sse_decode_voting_next_step(SseDeserializer deserializer);

  @protected
  VotingPirLayout sse_decode_voting_pir_layout(SseDeserializer deserializer);

  @protected
  VotingPreparedInfo sse_decode_voting_prepared_info(
      SseDeserializer deserializer);

  @protected
  VotingRoundInfo sse_decode_voting_round_info(SseDeserializer deserializer);

  @protected
  VotingRoundPlan sse_decode_voting_round_plan(SseDeserializer deserializer);

  @protected
  VotingRoundRecovery sse_decode_voting_round_recovery(
      SseDeserializer deserializer);

  @protected
  VotingRoundSession sse_decode_voting_round_session(
      SseDeserializer deserializer);

  @protected
  VotingServiceEndpoint sse_decode_voting_service_endpoint(
      SseDeserializer deserializer);

  @protected
  VotingShareDelegationRecord sse_decode_voting_share_delegation_record(
      SseDeserializer deserializer);

  @protected
  VotingSharePayload sse_decode_voting_share_payload(
      SseDeserializer deserializer);

  @protected
  VotingSharePlan sse_decode_voting_share_plan(SseDeserializer deserializer);

  @protected
  VotingSharePlanItem sse_decode_voting_share_plan_item(
      SseDeserializer deserializer);

  @protected
  VotingShareSubmissionPayload sse_decode_voting_share_submission_payload(
      SseDeserializer deserializer);

  @protected
  VotingShareTrackingSummary sse_decode_voting_share_tracking_summary(
      SseDeserializer deserializer);

  @protected
  VotingShareWorkflow sse_decode_voting_share_workflow(
      SseDeserializer deserializer);

  @protected
  VotingSignedVoteCommitment sse_decode_voting_signed_vote_commitment(
      SseDeserializer deserializer);

  @protected
  VotingTreeVoteConfirmation sse_decode_voting_tree_vote_confirmation(
      SseDeserializer deserializer);

  @protected
  VotingVanWitness sse_decode_voting_van_witness(SseDeserializer deserializer);

  @protected
  VotingVoteCommitStage sse_decode_voting_vote_commit_stage(
      SseDeserializer deserializer);

  @protected
  VotingVoteCommitments sse_decode_voting_vote_commitments(
      SseDeserializer deserializer);

  @protected
  VotingVoteConfirmation sse_decode_voting_vote_confirmation(
      SseDeserializer deserializer);

  @protected
  VotingVotePayloads sse_decode_voting_vote_payloads(
      SseDeserializer deserializer);

  @protected
  VotingVoteRecovery sse_decode_voting_vote_recovery(
      SseDeserializer deserializer);

  @protected
  VotingVoteSubmission sse_decode_voting_vote_submission(
      SseDeserializer deserializer);

  @protected
  ZsaHolding sse_decode_zsa_holding(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDartVault(
          DartVault self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMempool(
          Mempool self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNoteMigration(
          NoteMigration self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTransparentScanner(
          TransparentScanner self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMempool(
          Mempool self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTransparentScanner(
          TransparentScanner self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDartVault(
          DartVault self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNoteMigration(
          NoteMigration self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTransparentScanner(
          TransparentScanner self, SseSerializer serializer);

  @protected
  void
      sse_encode_DartFn_Inputs_list_prim_u_8_strict_Output_unit_AnyhowException(
          FutureOr<void> Function(Uint8List) self, SseSerializer serializer);

  @protected
  void sse_encode_DartOpaque(Object self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDartVault(
          DartVault self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMempool(
          Mempool self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNoteMigration(
          NoteMigration self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTransparentScanner(
          TransparentScanner self, SseSerializer serializer);

  @protected
  void sse_encode_StreamSink_String_Sse(
      RustStreamSink<String> self, SseSerializer serializer);

  @protected
  void sse_encode_StreamSink_dkg_status_Sse(
      RustStreamSink<DKGStatus> self, SseSerializer serializer);

  @protected
  void sse_encode_StreamSink_log_message_Sse(
      RustStreamSink<LogMessage> self, SseSerializer serializer);

  @protected
  void sse_encode_StreamSink_mempool_msg_Sse(
      RustStreamSink<MempoolMsg> self, SseSerializer serializer);

  @protected
  void sse_encode_StreamSink_migration_status_Sse(
      RustStreamSink<MigrationStatus> self, SseSerializer serializer);

  @protected
  void sse_encode_StreamSink_signing_event_Sse(
      RustStreamSink<SigningEvent> self, SseSerializer serializer);

  @protected
  void sse_encode_StreamSink_signing_status_Sse(
      RustStreamSink<SigningStatus> self, SseSerializer serializer);

  @protected
  void sse_encode_StreamSink_sync_progress_Sse(
      RustStreamSink<SyncProgress> self, SseSerializer serializer);

  @protected
  void sse_encode_StreamSink_voting_delegation_progress_Sse(
      RustStreamSink<VotingDelegationProgress> self, SseSerializer serializer);

  @protected
  void sse_encode_StreamSink_voting_vote_commit_stage_Sse(
      RustStreamSink<VotingVoteCommitStage> self, SseSerializer serializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_account(Account self, SseSerializer serializer);

  @protected
  void sse_encode_account_update(AccountUpdate self, SseSerializer serializer);

  @protected
  void sse_encode_addresses(Addresses self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_account_update(
      AccountUpdate self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_category(Category self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_coin(Coin self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_frost_params(
      FrostParams self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_64(
      PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_mempool_tx(
      MempoolTx self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_new_account(
      NewAccount self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_payment_options(
      PaymentOptions self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_pczt_package(
      PcztPackage self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_raptor_q_params(
      RaptorQParams self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_seed(Seed self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_signing_event(
      SigningEvent self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_voting_completed_vote_display(
      VotingCompletedVoteDisplay self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_voting_config(
      VotingConfig self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_voting_pir_layout(
      VotingPirLayout self, SseSerializer serializer);

  @protected
  void sse_encode_category(Category self, SseSerializer serializer);

  @protected
  void sse_encode_coin(Coin self, SseSerializer serializer);

  @protected
  void sse_encode_contact(Contact self, SseSerializer serializer);

  @protected
  void sse_encode_contact_match(ContactMatch self, SseSerializer serializer);

  @protected
  void sse_encode_db_account_preview(
      DbAccountPreview self, SseSerializer serializer);

  @protected
  void sse_encode_dkg_status(DKGStatus self, SseSerializer serializer);

  @protected
  void sse_encode_exchange_rate(ExchangeRate self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_folder(Folder self, SseSerializer serializer);

  @protected
  void sse_encode_frost_params(FrostParams self, SseSerializer serializer);

  @protected
  void sse_encode_frost_sign_params(
      FrostSignParams self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_isize(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_account(List<Account> self, SseSerializer serializer);

  @protected
  void sse_encode_list_category(List<Category> self, SseSerializer serializer);

  @protected
  void sse_encode_list_contact(List<Contact> self, SseSerializer serializer);

  @protected
  void sse_encode_list_contact_match(
      List<ContactMatch> self, SseSerializer serializer);

  @protected
  void sse_encode_list_db_account_preview(
      List<DbAccountPreview> self, SseSerializer serializer);

  @protected
  void sse_encode_list_folder(List<Folder> self, SseSerializer serializer);

  @protected
  void sse_encode_list_list_prim_u_8_strict(
      List<Uint8List> self, SseSerializer serializer);

  @protected
  void sse_encode_list_lwd_info(List<LWDInfo> self, SseSerializer serializer);

  @protected
  void sse_encode_list_memo(List<Memo> self, SseSerializer serializer);

  @protected
  void sse_encode_list_memo_cell(List<MemoCell> self, SseSerializer serializer);

  @protected
  void sse_encode_list_memo_row(List<MemoRow> self, SseSerializer serializer);

  @protected
  void sse_encode_list_memo_section(
      List<MemoSection> self, SseSerializer serializer);

  @protected
  void sse_encode_list_mempool_amount(
      List<MempoolAmount> self, SseSerializer serializer);

  @protected
  void sse_encode_list_mempool_note(
      List<MempoolNote> self, SseSerializer serializer);

  @protected
  void sse_encode_list_plugin_info(
      List<PluginInfo> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_32_loose(
      List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_32_strict(
      Uint32List self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_64_strict(
      Uint64List self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_usize_strict(
      Uint64List self, SseSerializer serializer);

  @protected
  void sse_encode_list_recipient(
      List<Recipient> self, SseSerializer serializer);

  @protected
  void sse_encode_list_record_string_f_64_bool(
      List<(String, double, bool)> self, SseSerializer serializer);

  @protected
  void sse_encode_list_record_u_32_f_64(
      List<(int, double)> self, SseSerializer serializer);

  @protected
  void sse_encode_list_restored_account(
      List<RestoredAccount> self, SseSerializer serializer);

  @protected
  void sse_encode_list_t_address_tx_count(
      List<TAddressTxCount> self, SseSerializer serializer);

  @protected
  void sse_encode_list_tx(List<Tx> self, SseSerializer serializer);

  @protected
  void sse_encode_list_tx_memo(List<TxMemo> self, SseSerializer serializer);

  @protected
  void sse_encode_list_tx_note(List<TxNote> self, SseSerializer serializer);

  @protected
  void sse_encode_list_tx_output(List<TxOutput> self, SseSerializer serializer);

  @protected
  void sse_encode_list_tx_plan_in(
      List<TxPlanIn> self, SseSerializer serializer);

  @protected
  void sse_encode_list_tx_plan_out(
      List<TxPlanOut> self, SseSerializer serializer);

  @protected
  void sse_encode_list_tx_spend(List<TxSpend> self, SseSerializer serializer);

  @protected
  void sse_encode_list_voting_ballot_intent(
      List<VotingBallotIntent> self, SseSerializer serializer);

  @protected
  void sse_encode_list_voting_completed_vote_choice(
      List<VotingCompletedVoteChoice> self, SseSerializer serializer);

  @protected
  void sse_encode_list_voting_config_round(
      List<VotingConfigRound> self, SseSerializer serializer);

  @protected
  void sse_encode_list_voting_delegation_recovery(
      List<VotingDelegationRecovery> self, SseSerializer serializer);

  @protected
  void sse_encode_list_voting_delegation_status(
      List<VotingDelegationStatus> self, SseSerializer serializer);

  @protected
  void sse_encode_list_voting_encrypted_share(
      List<VotingEncryptedShare> self, SseSerializer serializer);

  @protected
  void sse_encode_list_voting_next_step(
      List<VotingNextStep> self, SseSerializer serializer);

  @protected
  void sse_encode_list_voting_round_info(
      List<VotingRoundInfo> self, SseSerializer serializer);

  @protected
  void sse_encode_list_voting_round_session(
      List<VotingRoundSession> self, SseSerializer serializer);

  @protected
  void sse_encode_list_voting_service_endpoint(
      List<VotingServiceEndpoint> self, SseSerializer serializer);

  @protected
  void sse_encode_list_voting_share_delegation_record(
      List<VotingShareDelegationRecord> self, SseSerializer serializer);

  @protected
  void sse_encode_list_voting_share_payload(
      List<VotingSharePayload> self, SseSerializer serializer);

  @protected
  void sse_encode_list_voting_share_plan_item(
      List<VotingSharePlanItem> self, SseSerializer serializer);

  @protected
  void sse_encode_list_voting_share_submission_payload(
      List<VotingShareSubmissionPayload> self, SseSerializer serializer);

  @protected
  void sse_encode_list_voting_share_workflow(
      List<VotingShareWorkflow> self, SseSerializer serializer);

  @protected
  void sse_encode_list_voting_signed_vote_commitment(
      List<VotingSignedVoteCommitment> self, SseSerializer serializer);

  @protected
  void sse_encode_list_voting_vote_recovery(
      List<VotingVoteRecovery> self, SseSerializer serializer);

  @protected
  void sse_encode_list_zsa_holding(
      List<ZsaHolding> self, SseSerializer serializer);

  @protected
  void sse_encode_log_message(LogMessage self, SseSerializer serializer);

  @protected
  void sse_encode_lwd_info(LWDInfo self, SseSerializer serializer);

  @protected
  void sse_encode_memo(Memo self, SseSerializer serializer);

  @protected
  void sse_encode_memo_cell(MemoCell self, SseSerializer serializer);

  @protected
  void sse_encode_memo_row(MemoRow self, SseSerializer serializer);

  @protected
  void sse_encode_memo_section(MemoSection self, SseSerializer serializer);

  @protected
  void sse_encode_mempool_amount(MempoolAmount self, SseSerializer serializer);

  @protected
  void sse_encode_mempool_msg(MempoolMsg self, SseSerializer serializer);

  @protected
  void sse_encode_mempool_note(MempoolNote self, SseSerializer serializer);

  @protected
  void sse_encode_mempool_tx(MempoolTx self, SseSerializer serializer);

  @protected
  void sse_encode_migration_event(
      MigrationEvent self, SseSerializer serializer);

  @protected
  void sse_encode_migration_status(
      MigrationStatus self, SseSerializer serializer);

  @protected
  void sse_encode_new_account(NewAccount self, SseSerializer serializer);

  @protected
  void sse_encode_open_alias_resolution(
      OpenAliasResolution self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_frost_params(
      FrostParams? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_64(
      PlatformInt64? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_seed(Seed? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_8(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_voting_completed_vote_display(
      VotingCompletedVoteDisplay? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_voting_config(
      VotingConfig? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_voting_pir_layout(
      VotingPirLayout? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_String(List<String>? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
      Uint8List? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_recipient(
      List<Recipient>? self, SseSerializer serializer);

  @protected
  void sse_encode_payment_options(
      PaymentOptions self, SseSerializer serializer);

  @protected
  void sse_encode_pczt_package(PcztPackage self, SseSerializer serializer);

  @protected
  void sse_encode_plugin_info(PluginInfo self, SseSerializer serializer);

  @protected
  void sse_encode_pool_balance(PoolBalance self, SseSerializer serializer);

  @protected
  void sse_encode_raptor_q_params(RaptorQParams self, SseSerializer serializer);

  @protected
  void sse_encode_raw_open_alias_resolution(
      RawOpenAliasResolution self, SseSerializer serializer);

  @protected
  void sse_encode_receivers(Receivers self, SseSerializer serializer);

  @protected
  void sse_encode_recipient(Recipient self, SseSerializer serializer);

  @protected
  void sse_encode_record_string_f_64_bool(
      (String, double, bool) self, SseSerializer serializer);

  @protected
  void sse_encode_record_u_32_f_64(
      (int, double) self, SseSerializer serializer);

  @protected
  void sse_encode_restored_account(
      RestoredAccount self, SseSerializer serializer);

  @protected
  void sse_encode_sapling_params_status(
      SaplingParamsStatus self, SseSerializer serializer);

  @protected
  void sse_encode_seed(Seed self, SseSerializer serializer);

  @protected
  void sse_encode_signing_event(SigningEvent self, SseSerializer serializer);

  @protected
  void sse_encode_signing_status(SigningStatus self, SseSerializer serializer);

  @protected
  void sse_encode_sync_height(SyncHeight self, SseSerializer serializer);

  @protected
  void sse_encode_sync_progress(SyncProgress self, SseSerializer serializer);

  @protected
  void sse_encode_t_address_tx_count(
      TAddressTxCount self, SseSerializer serializer);

  @protected
  void sse_encode_tx(Tx self, SseSerializer serializer);

  @protected
  void sse_encode_tx_account(TxAccount self, SseSerializer serializer);

  @protected
  void sse_encode_tx_memo(TxMemo self, SseSerializer serializer);

  @protected
  void sse_encode_tx_note(TxNote self, SseSerializer serializer);

  @protected
  void sse_encode_tx_output(TxOutput self, SseSerializer serializer);

  @protected
  void sse_encode_tx_plan(TxPlan self, SseSerializer serializer);

  @protected
  void sse_encode_tx_plan_in(TxPlanIn self, SseSerializer serializer);

  @protected
  void sse_encode_tx_plan_out(TxPlanOut self, SseSerializer serializer);

  @protected
  void sse_encode_tx_spend(TxSpend self, SseSerializer serializer);

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_usize_array_4(UsizeArray4 self, SseSerializer serializer);

  @protected
  void sse_encode_voting_ballot_intent(
      VotingBallotIntent self, SseSerializer serializer);

  @protected
  void sse_encode_voting_chain_response(
      VotingChainResponse self, SseSerializer serializer);

  @protected
  void sse_encode_voting_completed_vote_choice(
      VotingCompletedVoteChoice self, SseSerializer serializer);

  @protected
  void sse_encode_voting_completed_vote_display(
      VotingCompletedVoteDisplay self, SseSerializer serializer);

  @protected
  void sse_encode_voting_config(VotingConfig self, SseSerializer serializer);

  @protected
  void sse_encode_voting_config_round(
      VotingConfigRound self, SseSerializer serializer);

  @protected
  void sse_encode_voting_delegation_build(
      VotingDelegationBuild self, SseSerializer serializer);

  @protected
  void sse_encode_voting_delegation_confirmation(
      VotingDelegationConfirmation self, SseSerializer serializer);

  @protected
  void sse_encode_voting_delegation_progress(
      VotingDelegationProgress self, SseSerializer serializer);

  @protected
  void sse_encode_voting_delegation_recovery(
      VotingDelegationRecovery self, SseSerializer serializer);

  @protected
  void sse_encode_voting_delegation_setup(
      VotingDelegationSetup self, SseSerializer serializer);

  @protected
  void sse_encode_voting_delegation_status(
      VotingDelegationStatus self, SseSerializer serializer);

  @protected
  void sse_encode_voting_delegation_submission(
      VotingDelegationSubmission self, SseSerializer serializer);

  @protected
  void sse_encode_voting_encrypted_share(
      VotingEncryptedShare self, SseSerializer serializer);

  @protected
  void sse_encode_voting_next_step(
      VotingNextStep self, SseSerializer serializer);

  @protected
  void sse_encode_voting_pir_layout(
      VotingPirLayout self, SseSerializer serializer);

  @protected
  void sse_encode_voting_prepared_info(
      VotingPreparedInfo self, SseSerializer serializer);

  @protected
  void sse_encode_voting_round_info(
      VotingRoundInfo self, SseSerializer serializer);

  @protected
  void sse_encode_voting_round_plan(
      VotingRoundPlan self, SseSerializer serializer);

  @protected
  void sse_encode_voting_round_recovery(
      VotingRoundRecovery self, SseSerializer serializer);

  @protected
  void sse_encode_voting_round_session(
      VotingRoundSession self, SseSerializer serializer);

  @protected
  void sse_encode_voting_service_endpoint(
      VotingServiceEndpoint self, SseSerializer serializer);

  @protected
  void sse_encode_voting_share_delegation_record(
      VotingShareDelegationRecord self, SseSerializer serializer);

  @protected
  void sse_encode_voting_share_payload(
      VotingSharePayload self, SseSerializer serializer);

  @protected
  void sse_encode_voting_share_plan(
      VotingSharePlan self, SseSerializer serializer);

  @protected
  void sse_encode_voting_share_plan_item(
      VotingSharePlanItem self, SseSerializer serializer);

  @protected
  void sse_encode_voting_share_submission_payload(
      VotingShareSubmissionPayload self, SseSerializer serializer);

  @protected
  void sse_encode_voting_share_tracking_summary(
      VotingShareTrackingSummary self, SseSerializer serializer);

  @protected
  void sse_encode_voting_share_workflow(
      VotingShareWorkflow self, SseSerializer serializer);

  @protected
  void sse_encode_voting_signed_vote_commitment(
      VotingSignedVoteCommitment self, SseSerializer serializer);

  @protected
  void sse_encode_voting_tree_vote_confirmation(
      VotingTreeVoteConfirmation self, SseSerializer serializer);

  @protected
  void sse_encode_voting_van_witness(
      VotingVanWitness self, SseSerializer serializer);

  @protected
  void sse_encode_voting_vote_commit_stage(
      VotingVoteCommitStage self, SseSerializer serializer);

  @protected
  void sse_encode_voting_vote_commitments(
      VotingVoteCommitments self, SseSerializer serializer);

  @protected
  void sse_encode_voting_vote_confirmation(
      VotingVoteConfirmation self, SseSerializer serializer);

  @protected
  void sse_encode_voting_vote_payloads(
      VotingVotePayloads self, SseSerializer serializer);

  @protected
  void sse_encode_voting_vote_recovery(
      VotingVoteRecovery self, SseSerializer serializer);

  @protected
  void sse_encode_voting_vote_submission(
      VotingVoteSubmission self, SseSerializer serializer);

  @protected
  void sse_encode_zsa_holding(ZsaHolding self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDartVault(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDartVault(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDartVaultPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_zkool_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDartVault');
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDartVault =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDartVaultPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDartVault(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDartVault(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDartVaultPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_zkool_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDartVault');
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDartVault =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDartVaultPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMempool(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMempool(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMempoolPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_zkool_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMempool');
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMempool =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMempoolPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMempool(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMempool(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMempoolPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_zkool_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMempool');
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMempool =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMempoolPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNoteMigration(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNoteMigration(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNoteMigrationPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_zkool_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNoteMigration');
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNoteMigration =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNoteMigrationPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNoteMigration(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNoteMigration(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNoteMigrationPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_zkool_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNoteMigration');
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNoteMigration =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNoteMigrationPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTransparentScanner(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTransparentScanner(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTransparentScannerPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_zkool_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTransparentScanner');
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTransparentScanner =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTransparentScannerPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTransparentScanner(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTransparentScanner(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTransparentScannerPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_zkool_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTransparentScanner');
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTransparentScanner =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTransparentScannerPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();
}
