// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class SyncHeight {
  final int pool;
  final int height;
  final int time;

  const SyncHeight({
    required this.pool,
    required this.height,
    required this.time,
  });

  @override
  int get hashCode => pool.hashCode ^ height.hashCode ^ time.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SyncHeight &&
          runtimeType == other.runtimeType &&
          pool == other.pool &&
          height == other.height &&
          time == other.time;
}
