// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'init.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `base_filter`, `frb_layer`
// These functions are ignored because they have generic arguments: `default_layer`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `FrbLogger`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `on_event`

/// Enable expert mode, which lowers the log filter to allow
/// sync, mempool, and memo target debug messages
/// while keeping everything else at `info`.
void setExpertMode({required bool enabled}) =>
    RustLib.instance.api.crateApiInitSetExpertMode(enabled: enabled);

Stream<LogMessage> setLogStream() =>
    RustLib.instance.api.crateApiInitSetLogStream();

@freezed
sealed class LogMessage with _$LogMessage {
  const factory LogMessage({
    required int level,
    required String message,
    String? span,
  }) = _LogMessage;
}
