// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'coin.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

String generateSeed() => RustLib.instance.api.crateApiKeyGenerateSeed();

bool isValidPhrase({required String phrase}) =>
    RustLib.instance.api.crateApiKeyIsValidPhrase(phrase: phrase);

bool isValidFvk({required String fvk, required Coin c}) =>
    RustLib.instance.api.crateApiKeyIsValidFvk(fvk: fvk, c: c);

bool isValidKey({required String key, required Coin c}) =>
    RustLib.instance.api.crateApiKeyIsValidKey(key: key, c: c);

bool isValidAddress({required String address}) =>
    RustLib.instance.api.crateApiKeyIsValidAddress(address: address);

bool isValidTransparentAddress({required String address, required Coin c}) =>
    RustLib.instance.api
        .crateApiKeyIsValidTransparentAddress(address: address, c: c);

bool isTexAddress({required String address, required Coin c}) =>
    RustLib.instance.api.crateApiKeyIsTexAddress(address: address, c: c);

int getKeyPools({required String key, required Coin c}) =>
    RustLib.instance.api.crateApiKeyGetKeyPools(key: key, c: c);
