// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../lib.dart';
import 'coin.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'pay.dart';

/// Version of the Zcash app open on the device, e.g. "3.9.3".
///
/// Fails with the device's status word when another app is open, which is
/// the cheapest way to tell the user to switch apps before asking for keys.
Future<String> ledgerAppVersion({
  required FutureOr<Uint8List> Function(Uint8List) exchange,
}) => RustLib.instance.api.crateApiLedgerLedgerAppVersion(exchange: exchange);

/// Unified full viewing key of ZIP-32 account `aindex` on the device
/// (transparent + orchard receivers). The user approves the export on the
/// device screen, so this blocks until they do.
Future<String> ledgerGetUfvk({
  required int aindex,
  required Coin c,
  required FutureOr<Uint8List> Function(Uint8List) exchange,
}) => RustLib.instance.api.crateApiLedgerLedgerGetUfvk(
  aindex: aindex,
  c: c,
  exchange: exchange,
);

/// Default unified address of a viewing key, for showing which account a
/// device key belongs to before the account exists in the database.
String ufvkDefaultAddress({required String ufvk, required Coin c}) =>
    RustLib.instance.api.crateApiLedgerUfvkDefaultAddress(ufvk: ufvk, c: c);

/// Signs a transaction plan on the Official Zcash app.
///
/// Streams `SigningEvent::Progress` while the device reviews and signs, then
/// `SigningEvent::Result` with the proven, finalized package ready for
/// `extract_transaction`. Errors, including a refusal on the device, close
/// the stream with the error.
Stream<SigningEvent> ledgerSignTransaction({
  required PcztPackage package,
  required Coin c,
  required FutureOr<Uint8List> Function(Uint8List) exchange,
}) => RustLib.instance.api.crateApiLedgerLedgerSignTransaction(
  package: package,
  c: c,
  exchange: exchange,
);
