// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'coin.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'mempool.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `run_mempool`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `fmt`

Future<Uint8List> getMempoolTx({required String txId, required Coin c}) =>
    RustLib.instance.api.crateApiMempoolGetMempoolTx(txId: txId, c: c);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Mempool>>
abstract class Mempool implements RustOpaqueInterface {
  Future<void> cancel();

  factory Mempool() => RustLib.instance.api.crateApiMempoolMempoolNew();

  Stream<MempoolMsg> run({required Coin c});
}

class MempoolAmount {
  final int account;
  final String name;
  final PlatformInt64 value;

  const MempoolAmount({
    required this.account,
    required this.name,
    required this.value,
  });

  @override
  int get hashCode => account.hashCode ^ name.hashCode ^ value.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MempoolAmount &&
          runtimeType == other.runtimeType &&
          account == other.account &&
          name == other.name &&
          value == other.value;
}

@freezed
sealed class MempoolMsg with _$MempoolMsg {
  const MempoolMsg._();

  const factory MempoolMsg.blockHeight(
    int field0,
  ) = MempoolMsg_BlockHeight;
  const factory MempoolMsg.txId(
    MempoolTx field0,
  ) = MempoolMsg_TxId;
}

class MempoolNote {
  final int account;
  final String name;
  final PlatformInt64 value;
  final int pool;
  final int scope;
  final Uint8List? diversifier;
  final PlatformInt64? diversifierIndex;
  final String? address;
  final String? memo;

  const MempoolNote({
    required this.account,
    required this.name,
    required this.value,
    required this.pool,
    required this.scope,
    this.diversifier,
    this.diversifierIndex,
    this.address,
    this.memo,
  });

  @override
  int get hashCode =>
      account.hashCode ^
      name.hashCode ^
      value.hashCode ^
      pool.hashCode ^
      scope.hashCode ^
      diversifier.hashCode ^
      diversifierIndex.hashCode ^
      address.hashCode ^
      memo.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MempoolNote &&
          runtimeType == other.runtimeType &&
          account == other.account &&
          name == other.name &&
          value == other.value &&
          pool == other.pool &&
          scope == other.scope &&
          diversifier == other.diversifier &&
          diversifierIndex == other.diversifierIndex &&
          address == other.address &&
          memo == other.memo;
}

class MempoolTx {
  final String txid;
  final List<MempoolAmount> amounts;
  final List<MempoolNote> notes;
  final int size;

  const MempoolTx({
    required this.txid,
    required this.amounts,
    required this.notes,
    required this.size,
  });

  @override
  int get hashCode =>
      txid.hashCode ^ amounts.hashCode ^ notes.hashCode ^ size.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MempoolTx &&
          runtimeType == other.runtimeType &&
          txid == other.txid &&
          amounts == other.amounts &&
          notes == other.notes &&
          size == other.size;
}
