// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'coin.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'migrate.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `execute`, `observe_state`, `run_migration`, `sample_delay`, `status_from`, `wait_for_next_height`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `Executed`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// Single-shot step (kept for FRB generated-code compatibility).
Future<MigrationEvent> stepMigration({required Coin c}) =>
    RustLib.instance.api.crateApiMigrateStepMigration(c: c);

/// Stub kept for FRB generated-code compatibility.
Future<MigrationStatus> getMigrationStatus({required Coin c}) =>
    RustLib.instance.api.crateApiMigrateGetMigrationStatus(c: c);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<NoteMigration>>
abstract class NoteMigration implements RustOpaqueInterface {
  Future<void> cancel();

  factory NoteMigration() =>
      RustLib.instance.api.crateApiMigrateNoteMigrationNew();

  Stream<MigrationStatus> run({required Coin c, required BigInt meanDelayMs});

  /// Supplies a height observed by the shared Dart block-height service.
  void updateHeight({required int height});
}

@freezed
sealed class MigrationEvent with _$MigrationEvent {
  const MigrationEvent._();

  const factory MigrationEvent.splitComplete({required BigInt fee}) =
      MigrationEvent_SplitComplete;
  const factory MigrationEvent.migrateComplete({required BigInt fee}) =
      MigrationEvent_MigrateComplete;
  const factory MigrationEvent.complete() = MigrationEvent_Complete;
  const factory MigrationEvent.nothingToDo() = MigrationEvent_NothingToDo;
  const factory MigrationEvent.error({required String message}) =
      MigrationEvent_Error;
}

/// Current migration status — streamed to Flutter by run_migration().
class MigrationStatus {
  final String phase;
  final BigInt splitFees;
  final BigInt migrateFees;
  final BigInt totalFees;
  final int sdNotesCount;
  final int nonSdNotesCount;
  final int ironwoodSdCount;
  final double progress;
  final String nextAction;
  final String workSummary;

  const MigrationStatus({
    required this.phase,
    required this.splitFees,
    required this.migrateFees,
    required this.totalFees,
    required this.sdNotesCount,
    required this.nonSdNotesCount,
    required this.ironwoodSdCount,
    required this.progress,
    required this.nextAction,
    required this.workSummary,
  });

  @override
  int get hashCode =>
      phase.hashCode ^
      splitFees.hashCode ^
      migrateFees.hashCode ^
      totalFees.hashCode ^
      sdNotesCount.hashCode ^
      nonSdNotesCount.hashCode ^
      ironwoodSdCount.hashCode ^
      progress.hashCode ^
      nextAction.hashCode ^
      workSummary.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MigrationStatus &&
          runtimeType == other.runtimeType &&
          phase == other.phase &&
          splitFees == other.splitFees &&
          migrateFees == other.migrateFees &&
          totalFees == other.totalFees &&
          sdNotesCount == other.sdNotesCount &&
          nonSdNotesCount == other.nonSdNotesCount &&
          ironwoodSdCount == other.ironwoodSdCount &&
          progress == other.progress &&
          nextAction == other.nextAction &&
          workSummary == other.workSummary;
}
