// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'coin.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'network.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `coingecko_client`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

Future<void> initDatadir({required String directory}) =>
    RustLib.instance.api.crateApiNetworkInitDatadir(directory: directory);

Future<bool> isIronwoodActive({required Coin c}) =>
    RustLib.instance.api.crateApiNetworkIsIronwoodActive(c: c);

Future<int> getCurrentHeight({required Coin c}) =>
    RustLib.instance.api.crateApiNetworkGetCurrentHeight(c: c);

Future<double> getCoingeckoPrice({
  required String api,
  required String currency,
}) => RustLib.instance.api.crateApiNetworkGetCoingeckoPrice(
  api: api,
  currency: currency,
);

Future<List<String>> getSupportedVsCurrencies({required String api}) =>
    RustLib.instance.api.crateApiNetworkGetSupportedVsCurrencies(api: api);

/// Returns the ZEC price in both `from_currency` and `to_currency`.
/// The exchange rate from `from_currency` to `to_currency` can be computed as
/// `to_price / from_price`.
Future<ExchangeRate> getExchangeRate({
  required String api,
  required String fromCurrency,
  required String toCurrency,
}) => RustLib.instance.api.crateApiNetworkGetExchangeRate(
  api: api,
  fromCurrency: fromCurrency,
  toCurrency: toCurrency,
);

Future<String> getNetworkName({required Coin c}) =>
    RustLib.instance.api.crateApiNetworkGetNetworkName(c: c);

Future<List<LWDInfo>> queryLwdList({required int coin}) =>
    RustLib.instance.api.crateApiNetworkQueryLwdList(coin: coin);

/// True when `url` is a mixnet-native server address
/// (`nym://<identity>.<encryption>@<gateway>`).
///
/// Always exported so the generated bindings do not depend on the `nym`
/// feature; without it no URL is a mixnet address.
bool isValidNymUrl({required String url}) =>
    RustLib.instance.api.crateApiNetworkIsValidNymUrl(url: url);

@freezed
sealed class ExchangeRate with _$ExchangeRate {
  const factory ExchangeRate({
    required double fromPrice,
    required double toPrice,
    required String fromCurrency,
    required String toCurrency,
  }) = _ExchangeRate;
}

@freezed
sealed class LWDInfo with _$LWDInfo {
  const factory LWDInfo({
    required String url,
    required bool isTor,
    required int height,
    required String status,
    required int uptime,
    required String version,
    required int ping,
  }) = _LWDInfo;
}
