// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../lib.dart';
import '../pay.dart';
import 'coin.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'pay.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `borrow_decode`, `clone`, `clone`, `decode`, `encode`, `fmt`, `fmt`

Future<String> buildPuri({required List<Recipient> recipients}) =>
    RustLib.instance.api.crateApiPayBuildPuri(recipients: recipients);

Future<PcztPackage> prepare({
  required List<Recipient> recipients,
  required PaymentOptions options,
  required Coin c,
}) => RustLib.instance.api.crateApiPayPrepare(
  recipients: recipients,
  options: options,
  c: c,
);

/// Prepare a migration transaction (splitting or migrating).
/// Uses `migration=true` to allow Orchard outputs when Ironwood is active.
Future<PcztPackage> prepareMigration({
  required List<Recipient> recipients,
  required int srcPools,
  required Coin c,
}) => RustLib.instance.api.crateApiPayPrepareMigration(
  recipients: recipients,
  srcPools: srcPools,
  c: c,
);

Future<PcztPackage> signTransaction({
  required PcztPackage pczt,
  required Coin c,
}) => RustLib.instance.api.crateApiPaySignTransaction(pczt: pczt, c: c);

/// Proves and finalizes a PCZT signed by an external airgapped signer
/// (Keystone, Cupcake). Uses no spending keys, so it works on watch-only
/// accounts; pass the result to [`extract_transaction`] to broadcast.
Future<PcztPackage> proveAndFinalize({
  required PcztPackage pczt,
  required Coin c,
}) => RustLib.instance.api.crateApiPayProveAndFinalize(pczt: pczt, c: c);

/// Rewrites a PCZT into the encoding a Keystone reads.
///
/// Cake pins an older `pczt` than the device's firmware, and the two disagree
/// on enough of the v2 layout that each silently misreads the other. Translate
/// on the way out, and [`pczt_from_keystone`] on the way back.
Future<Uint8List> pcztToKeystone({required List<int> pczt}) =>
    RustLib.instance.api.crateApiPayPcztToKeystone(pczt: pczt);

/// Rewrites a PCZT signed by a Keystone back into the encoding Cake uses.
Future<Uint8List> pcztFromKeystone({required List<int> pczt}) =>
    RustLib.instance.api.crateApiPayPcztFromKeystone(pczt: pczt);

/// Rewrites a PCZT into the encoding the Cupcake signer reads.
///
/// Cupcake parses PCZTs with an older `pczt` than this wallet writes; the
/// layouts share a name but not their fields, so send it this rather than the
/// wallet's own bytes.
Future<Uint8List> pcztToCupcake({required List<int> pczt}) =>
    RustLib.instance.api.crateApiPayPcztToCupcake(pczt: pczt);

/// Rewrites a PCZT signed by the Cupcake signer back into the encoding this
/// wallet uses. [`prove_and_finalize`] also accepts one directly.
Future<Uint8List> pcztFromCupcake({required List<int> pczt}) =>
    RustLib.instance.api.crateApiPayPcztFromCupcake(pczt: pczt);

/// Takes a Keystone's signatures into the PCZT this wallet built.
///
/// The device redacts prover-only fields, so its reply cannot be proved on its
/// own; `original` supplies those, `signed` supplies only the signatures.
Future<Uint8List> pcztApplyKeystoneSignatures({
  required List<int> original,
  required List<int> signed,
}) => RustLib.instance.api.crateApiPayPcztApplyKeystoneSignatures(
  original: original,
  signed: signed,
);

/// Builds a `zcash-sign-batch` request for a Keystone from one or more PCZTs in
/// Cake's dialect.
///
/// The batch path returns only signatures rather than a whole PCZT, so the reply
/// is far smaller over animated QR. It carries shielded spends only; a PCZT with
/// transparent inputs (a shield) must use the single [`pczt_to_keystone`] path.
Future<Uint8List> pcztToBatchRequest({required List<Uint8List> pczts}) =>
    RustLib.instance.api.crateApiPayPcztToBatchRequest(pczts: pczts);

/// Takes a Keystone's `zcash-batch-sig-result` reply into the PCZT this wallet
/// built. `original` is the single PCZT sent in the batch; `response` carries
/// only its spend-auth signatures.
Future<Uint8List> pcztApplyBatchSignatures({
  required List<int> original,
  required List<int> response,
}) => RustLib.instance.api.crateApiPayPcztApplyBatchSignatures(
  original: original,
  response: response,
);

Future<Uint8List> extractTransaction({required PcztPackage package}) =>
    RustLib.instance.api.crateApiPayExtractTransaction(package: package);

/// Serialize a PCZT for transport between participants.
///
/// Uses bincode's `standard()` config so the bytes are interchangeable with
/// zkool_graphql, whose `prepareSend` / `frostSign` use the same config. The
/// two used to disagree (`legacy()` here), which made it impossible for an app
/// user and a zkool_graphql user to co-sign a FROST transaction.
Future<Uint8List> packTransaction({required PcztPackage pczt}) =>
    RustLib.instance.api.crateApiPayPackTransaction(pczt: pczt);

Future<PcztPackage> unpackTransaction({required List<int> bytes}) =>
    RustLib.instance.api.crateApiPayUnpackTransaction(bytes: bytes);

Future<String> broadcastTransaction({
  required int height,
  required List<int> txBytes,
  required Coin c,
}) => RustLib.instance.api.crateApiPayBroadcastTransaction(
  height: height,
  txBytes: txBytes,
  c: c,
);

TxPlan toPlan({required PcztPackage package, required Coin c}) =>
    RustLib.instance.api.crateApiPayToPlan(package: package, c: c);

Future<String> send({
  required int height,
  required List<int> data,
  required Coin c,
}) => RustLib.instance.api.crateApiPaySend(height: height, data: data, c: c);

Future<void> storePendingTx({
  required int height,
  required List<int> txid,
  double? price,
  int? category,
  required Coin c,
}) => RustLib.instance.api.crateApiPayStorePendingTx(
  height: height,
  txid: txid,
  price: price,
  category: category,
  c: c,
);

List<Recipient>? parsePaymentUri({required String uri}) =>
    RustLib.instance.api.crateApiPayParsePaymentUri(uri: uri);

class PaymentOptions {
  final int srcPools;
  final bool recipientPaysFee;
  final bool smartTransparent;
  final int? category;

  const PaymentOptions({
    required this.srcPools,
    required this.recipientPaysFee,
    required this.smartTransparent,
    this.category,
  });

  @override
  int get hashCode =>
      srcPools.hashCode ^
      recipientPaysFee.hashCode ^
      smartTransparent.hashCode ^
      category.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PaymentOptions &&
          runtimeType == other.runtimeType &&
          srcPools == other.srcPools &&
          recipientPaysFee == other.recipientPaysFee &&
          smartTransparent == other.smartTransparent &&
          category == other.category;
}

@freezed
sealed class PcztPackage with _$PcztPackage {
  const factory PcztPackage({
    required Uint8List pczt,
    required UsizeArray4 nSpends,
    required Uint64List saplingIndices,
    required Uint64List orchardIndices,
    required Uint64List ironwoodIndices,
    required bool canSign,
    required bool canBroadcast,
    double? price,
    int? category,
    required bool isIssuance,
  }) = _PcztPackage;
}

@freezed
sealed class SigningEvent with _$SigningEvent {
  const SigningEvent._();

  const factory SigningEvent.progress(String field0) = SigningEvent_Progress;
  const factory SigningEvent.result(PcztPackage field0) = SigningEvent_Result;
}
