// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../lib.dart';
import '../pay.dart';
import 'coin.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'pay.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `borrow_decode`, `decode`, `encode`

Future<String> buildPuri({required List<Recipient> recipients}) =>
    RustLib.instance.api.crateApiPayBuildPuri(recipients: recipients);

Future<PcztPackage> prepare(
        {required List<Recipient> recipients,
        required PaymentOptions options,
        required Coin c}) =>
    RustLib.instance.api
        .crateApiPayPrepare(recipients: recipients, options: options, c: c);

/// Prepare a migration transaction (splitting or migrating).
/// Uses `migration=true` to allow Orchard outputs when Ironwood is active.
Future<PcztPackage> prepareMigration(
        {required List<Recipient> recipients,
        required int srcPools,
        required Coin c}) =>
    RustLib.instance.api.crateApiPayPrepareMigration(
        recipients: recipients, srcPools: srcPools, c: c);

Future<PcztPackage> signTransaction(
        {required PcztPackage pczt, required Coin c}) =>
    RustLib.instance.api.crateApiPaySignTransaction(pczt: pczt, c: c);

/// Proves and finalizes a PCZT signed by an external airgapped signer
/// (Keystone, Cupcake). Uses no spending keys, so it works on watch-only
/// accounts; pass the result to [`extract_transaction`] to broadcast.
Future<PcztPackage> proveAndFinalize(
        {required PcztPackage pczt, required Coin c}) =>
    RustLib.instance.api.crateApiPayProveAndFinalize(pczt: pczt, c: c);

/// Rewrites a PCZT into the encoding a Keystone reads.
///
/// Cake pins an older `pczt` than the device's firmware, and the two disagree
/// on enough of the v2 layout that each silently misreads the other. Translate
/// on the way out, and [`pczt_from_keystone`] on the way back.
Future<Uint8List> pcztToKeystone({required List<int> pczt}) =>
    RustLib.instance.api.crateApiPayPcztToKeystone(pczt: pczt);

/// Rewrites a PCZT signed by a Keystone back into the encoding Cake uses.
Future<Uint8List> pcztFromKeystone({required List<int> pczt}) =>
    RustLib.instance.api.crateApiPayPcztFromKeystone(pczt: pczt);

Future<Uint8List> extractTransaction({required PcztPackage package}) =>
    RustLib.instance.api.crateApiPayExtractTransaction(package: package);

Future<Uint8List> packTransaction({required PcztPackage pczt}) =>
    RustLib.instance.api.crateApiPayPackTransaction(pczt: pczt);

Future<PcztPackage> unpackTransaction({required List<int> bytes}) =>
    RustLib.instance.api.crateApiPayUnpackTransaction(bytes: bytes);

Future<String> broadcastTransaction(
        {required int height, required List<int> txBytes, required Coin c}) =>
    RustLib.instance.api.crateApiPayBroadcastTransaction(
        height: height, txBytes: txBytes, c: c);

TxPlan toPlan({required PcztPackage package, required Coin c}) =>
    RustLib.instance.api.crateApiPayToPlan(package: package, c: c);

Future<String> send(
        {required int height, required List<int> data, required Coin c}) =>
    RustLib.instance.api.crateApiPaySend(height: height, data: data, c: c);

Future<void> storePendingTx(
        {required int height,
        required List<int> txid,
        double? price,
        int? category,
        required Coin c}) =>
    RustLib.instance.api.crateApiPayStorePendingTx(
        height: height, txid: txid, price: price, category: category, c: c);

/// Get the persisted coin-selection mode preference.
/// Returns 0 for fee optimisation, 1 for privacy preservation.
Future<int> getCoinSelectionMode({required Coin c}) =>
    RustLib.instance.api.crateApiPayGetCoinSelectionMode(c: c);

/// Persist the coin-selection mode preference.
/// Pass 0 for fee optimisation, 1 for privacy preservation.
Future<void> setCoinSelectionMode({required int mode, required Coin c}) =>
    RustLib.instance.api.crateApiPaySetCoinSelectionMode(mode: mode, c: c);

List<Recipient>? parsePaymentUri({required String uri}) =>
    RustLib.instance.api.crateApiPayParsePaymentUri(uri: uri);

class PaymentOptions {
  final int srcPools;
  final bool recipientPaysFee;
  final bool smartTransparent;
  final int? category;

  /// Coin-selection mode: 0 = fee minimisation, 1 = privacy preservation.
  final int mode;

  const PaymentOptions({
    required this.srcPools,
    required this.recipientPaysFee,
    required this.smartTransparent,
    this.category,
    required this.mode,
  });

  @override
  int get hashCode =>
      srcPools.hashCode ^
      recipientPaysFee.hashCode ^
      smartTransparent.hashCode ^
      category.hashCode ^
      mode.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PaymentOptions &&
          runtimeType == other.runtimeType &&
          srcPools == other.srcPools &&
          recipientPaysFee == other.recipientPaysFee &&
          smartTransparent == other.smartTransparent &&
          category == other.category &&
          mode == other.mode;
}

@freezed
sealed class PcztPackage with _$PcztPackage {
  const factory PcztPackage({
    required Uint8List pczt,
    required UsizeArray4 nSpends,
    required Uint64List saplingIndices,
    required Uint64List orchardIndices,
    required Uint64List ironwoodIndices,
    required bool canSign,
    required bool canBroadcast,
    double? price,
    int? category,
    required bool isIssuance,
  }) = _PcztPackage;
}

@freezed
sealed class SigningEvent with _$SigningEvent {
  const SigningEvent._();

  const factory SigningEvent.progress(
    String field0,
  ) = SigningEvent_Progress;
  const factory SigningEvent.result(
    PcztPackage field0,
  ) = SigningEvent_Result;
}
