// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'coin.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'plugin.freezed.dart';

/// List all installed plugins.
Future<List<PluginInfo>> listPlugins({required Coin c}) =>
    RustLib.instance.api.crateApiPluginListPlugins(c: c);

/// Install a plugin from a URL (downloads a .zip archive).
Future<PluginInfo> installPlugin({required String url, required Coin c}) =>
    RustLib.instance.api.crateApiPluginInstallPlugin(url: url, c: c);

/// Remove a plugin completely (files + DB).
Future<void> removePlugin({required String id, required Coin c}) =>
    RustLib.instance.api.crateApiPluginRemovePlugin(id: id, c: c);

/// Enable or disable a plugin.
Future<void> setPluginEnabled(
        {required String id, required bool enabled, required Coin c}) =>
    RustLib.instance.api
        .crateApiPluginSetPluginEnabled(id: id, enabled: enabled, c: c);

/// Parse a memo with all matching plugins.
/// `memo_bytes` is the full 512-byte memo (including the 0xFF type byte).
/// Returns sections from all plugins whose prefixes match.
Future<List<MemoSection>> parseMemoWithPlugins(
        {required List<int> memoBytes, required Coin c}) =>
    RustLib.instance.api
        .crateApiPluginParseMemoWithPlugins(memoBytes: memoBytes, c: c);

/// Initialize the plugin system at app startup (creates plugins directory).
void initPlugins() => RustLib.instance.api.crateApiPluginInitPlugins();

/// A single typed cell in a memo table.
@freezed
sealed class MemoCell with _$MemoCell {
  const factory MemoCell({
    required String cellType,
    required String value,
  }) = _MemoCell;
}

/// A row of cells in a memo section.
@freezed
sealed class MemoRow with _$MemoRow {
  const factory MemoRow({
    required List<MemoCell> cells,
  }) = _MemoRow;
}

/// A parsed memo section — a titled table.
@freezed
sealed class MemoSection with _$MemoSection {
  const factory MemoSection({
    required String title,
    required List<String> headers,
    required List<MemoRow> rows,
  }) = _MemoSection;
}

/// Plugin metadata visible to the UI.
@freezed
sealed class PluginInfo with _$PluginInfo {
  const factory PluginInfo({
    required String id,
    required String name,
    required String version,
    String? author,
    String? description,
    required bool enabled,
    required List<String> types,
    required List<String> memoPrefixes,
  }) = _PluginInfo;
}
