// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `download_and_verify`, `resolve_params_dir`, `set_sapling_params_dir`

/// Check whether Sapling parameters are available.
///
/// With `bundled-sapling-params` they are compiled into the binary and always
/// considered available. Otherwise checks whether they are on disk.
SaplingParamsStatus checkSaplingParams() =>
    RustLib.instance.api.crateApiSaplingCheckSaplingParams();

/// Download Sapling parameters from the z.cash download server.
///
/// Verifies file size and Blake2b hash upon download.
/// Safe to call even if they are already downloaded (no-op if valid).
/// With `bundled-sapling-params` the parameters are compiled into the binary
/// and this is a no-op.
Future<void> downloadSaplingParams() =>
    RustLib.instance.api.crateApiSaplingDownloadSaplingParams();

/// Status of the Sapling proving parameters on disk.
class SaplingParamsStatus {
  final bool downloaded;

  const SaplingParamsStatus({required this.downloaded});

  @override
  int get hashCode => downloaded.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SaplingParamsStatus &&
          runtimeType == other.runtimeType &&
          downloaded == other.downloaded;
}
