// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'coin.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<TransparentScanner>>
abstract class TransparentScanner implements RustOpaqueInterface {
  Future<void> cancel();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<TransparentScanner> newInstance() =>
      RustLib.instance.api.crateApiSweepTransparentScannerNew();

  Stream<String> run(
      {required int endHeight, required int gapLimit, required Coin c});
}
