// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`

Future<DartVault> initVault(
        {required FutureOr<void> Function(Uint8List) append}) =>
    RustLib.instance.api.crateApiVaultInitVault(append: append);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<DartVault>>
abstract class DartVault implements RustOpaqueInterface {
  Future<List<RestoredAccount>> recover(
      {required List<int> vaultBytes, required String masterPassword});

  Future<List<RestoredAccount>> recoverWithPrf(
      {required List<int> vaultBytes,
      required String deviceIdStr,
      required List<int> prfOutput});

  Future<void> registerDevice(
      {required List<int> initBytes,
      required String masterPassword,
      required String deviceIdStr,
      required List<int> prfOutput});

  Future<Uint8List> setMasterPassword(
      {String? oldPassword, required String newPassword, Uint8List? oldBytes});

  Future<void> storeAccount(
      {required int timestamp,
      required String name,
      required String seed,
      required int aindex,
      required bool useInternal,
      required int birthHeight,
      required List<int> pk});

  Future<void> test();
}

class RestoredAccount {
  final int timestamp;
  final String name;
  final String seed;
  final int aindex;
  final bool useInternal;
  final int birthHeight;

  const RestoredAccount({
    required this.timestamp,
    required this.name,
    required this.seed,
    required this.aindex,
    required this.useInternal,
    required this.birthHeight,
  });

  @override
  int get hashCode =>
      timestamp.hashCode ^
      name.hashCode ^
      seed.hashCode ^
      aindex.hashCode ^
      useInternal.hashCode ^
      birthHeight.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RestoredAccount &&
          runtimeType == other.runtimeType &&
          timestamp == other.timestamp &&
          name == other.name &&
          seed == other.seed &&
          aindex == other.aindex &&
          useInternal == other.useInternal &&
          birthHeight == other.birthHeight;
}
