// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'coin.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'zsa.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`, `from`

Future<List<ZsaHolding>> listZsaHoldings({required Coin c}) =>
    RustLib.instance.api.crateApiZsaListZsaHoldings(c: c);

/// Set or update the human-readable name for a ZSA asset.
/// Pass an empty string to clear the name (reverting to the hex fallback display).
Future<void> setAssetName(
        {required PlatformInt64 idAsset,
        required String name,
        required Coin c}) =>
    RustLib.instance.api
        .crateApiZsaSetAssetName(idAsset: idAsset, name: name, c: c);

/// Check whether ZSA (Zcash Shielded Assets) is available on the current network.
///
/// ZSA is enabled when the network's [`OrchardMode`] is set to [`OrchardMode::Zsa`].
Future<bool> isZsaAvailable({required Coin c}) =>
    RustLib.instance.api.crateApiZsaIsZsaAvailable(c: c);

/// A ZSA token holding representing a balance of a specific asset.
@freezed
sealed class ZsaHolding with _$ZsaHolding {
  const factory ZsaHolding({
    required PlatformInt64 idAsset,
    required Uint8List assetDescHash,
    required String assetName,
    required Uint8List ik,
    required Uint8List assetBase,
    required bool finalized,
    required int firstSeenHeight,
    required BigInt balance,
  }) = _ZsaHolding;
}
